# Generated by Django 5.1.5 on 2025-04-02 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='architect',
        ),
        migrations.AddField(
            model_name='building',
            name='architects',
            field=models.ManyToManyField(related_name='buildings', to='content.architect'),
        ),
        migrations.AlterField(
            model_name='building',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='content.style'),
        ),
    ]
