# Generated by Django 5.1.5 on 2025-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_building_architect_building_architects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(null=True, upload_to='images/buildings'),
        ),
    ]
