# Generated by Django 5.1.5 on 2025-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
