# Generated by Django 5.1.5 on 2025-04-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_architect_bio_style_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildings'),
        ),
    ]
