# Generated by Django 5.1.5 on 2025-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_building_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
